# Generated by Django 6.0.7 on 2026-09-07 08:09

import random

from django.db import migrations, models


def backfill_order_refs(apps, schema_editor):
    """Existing orders have no order_ref; give each a unique one."""
    Order = apps.get_model('store', 'Order')
    used = set(Order.objects.exclude(order_ref='').values_list('order_ref', flat=True))
    for order in Order.objects.filter(order_ref=''):
        while True:
            ref = f"OB{random.randint(10**9, 10**10 - 1)}"
            if ref not in used:
                break
        used.add(ref)
        order.order_ref = ref
        order.save(update_fields=['order_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('verifying', 'Verifying Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.RunPython(backfill_order_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_ref',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
