# Generated by Django 6.0.7 on 2026-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_order_ref_order_paid_at_order_payment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
