# Generated by Django 6.0.7 on 2026-09-07 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_stockalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
