# Generated by Django 6.0.7 on 2026-09-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_stockalert_user_alter_stockalert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
