# Generated by Django 6.0.7 on 2026-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_review_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP User'),
        ),
    ]
